export const items = [
  {
    id: "1",
    title: "Clothes",
    description: "Explore our stylish and comfortable clothing collection for all seasons.",
    imageUrl: "/clothes.jpg",
    linkUrl: "/marketplace/clothes",
  },
  {
    id: "2",
    title: "Phones",
    description: "Discover the latest smartphones with cutting-edge technology and features.",
    imageUrl: "/phone.jpg",
    linkUrl: "/page1",
  },
  {
    id: "3",
    title: "Chairs",
    description: "Find ergonomic and elegant chairs perfect for your home or office setup.",
    imageUrl: "/chairs.jpg",
    linkUrl: "/page1",
  },
  {
    id: "4",
    title: "Bags",
    description: "Shop trendy and durable bags for every occasion and style preference.",
    imageUrl: "/bags.jpg",
    linkUrl: "/page1",
  },
  {
    id: "5",
    title: "Shoes",
    description: "Step into comfort and style with our diverse shoe selection for all ages.",
    imageUrl: "/shoes.jpg",
    linkUrl: "/page1",
  },
  {
    id: "6",
    title: "Cars",
    description: "Browse a wide range of cars, from compact city models to luxury vehicles.",
    imageUrl: "/car.jpg",
    linkUrl: "/page1",
  },
  {
    id: "7",
    title: "Home Appliances",
    description: "Upgrade your home with reliable and energy-efficient appliances.",
    imageUrl: "/home-app.jpg",
    linkUrl: "/page1",
  },
  {
    id: "8",
    title: "Laptops",
    description: "Choose from powerful laptops tailored for work, gaming, and everyday use.",
    imageUrl: "/laptop.jpg",
    linkUrl: "/page1",
  },
  {
    id: "9",
    title: "Books",
    description: "Dive into our extensive collection of books across all genres and interests.",
    imageUrl: "/books.jpg",
    linkUrl: "/page1",
  },
  {
    id: "10",
    title: "Make Up",
    description: "Enhance your beauty with top-quality makeup products from trusted brands.",
    imageUrl: "/make-up.jpg",
    linkUrl: "/page2",
  },
];
